<?php

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the #first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even
# valued terms.

$j = 1;
$i = 0;
$sum =0;
$sum2 = 0;

for ($sum=$i+$j, $i=$j, $j=$sum; $sum < 100;) {
	
}

//for ($i = 0; $i < 10; $i+$j) {
//	
//	$j = $i;
//	$j = sum;
//		
//	floor(fmod($sum,2))==0?$sum2+=$sum:0;
//	echo $sum . "<br />";
//	
//	
//}

var_dump ($sum);